[project]
name = "inspertorchaudio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Fabio Ayres", email = "fabioja@insper.edu.br" }
]
requires-python = ">=3.13"
dependencies = [
    "resampy>=0.4.3",
    "soundfile>=0.13.1",
    "torch>=2.7.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "isort>=6.0.1",
    "pylint>=3.3.7",
    "pytest>=8.4.0",
    "yapf>=0.43.0",
]
